import AllPosts from "@pagesComps/Posts/AllPosts";

export const metadata = {
  title: "Newspaper - Posts",
  description: "Generated by create next app",
};

const Posts = () => {
  return (
    <div>
      <AllPosts />
    </div>
  );
};

export default Posts;
