import Dashboard from "@pagesComps/Dashboard";

//using google font
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Newspaper - Dashboard",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Dashboard />
    </>
  );
}
