import AddNewPost from "@pagesComps/Posts/AddNewPost";

export const metadata = {
  title: "Newspaper - Add New Post",
  description: "Generated by create next app",
};

const AddNew = () => {
  return (
    <div>
      <AddNewPost />
    </div>
  );
};

export default AddNew;
