import Head from "next/head";
import AddNewPost from "@pagesComps/Posts/AddNewPost";

const AddNew = () => {
  return (
    <div>
      <Head>
        <title>Newspaper - Add New Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddNewPost />
    </div>
  );
};

export default AddNew;
