import Head from "next/head";
import AllPosts from "@pagesComps/Posts/AllPosts";

const Posts = () => {
  return (
    <div>
      <Head>
        <title>Newspaper - Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AllPosts />
    </div>
  );
};

export default Posts;
