import { redirectToLoginPage } from "@/redux/auth/helper/redirectToLoginPage";
import { wrapper } from "@/redux/store";
import Dashboard from "@pagesComps/Dashboard";
import { GetServerSideProps } from "next";
import Head from "next/head";

//using google font
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Newspaper - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
}

export const getServerSideProps: GetServerSideProps =
  // eslint-disable-next-line @typescript-eslint/require-await
  wrapper.getServerSideProps((store) => async () => {
    /** Redirect un-authenticated user into login page */
    const willRedirect = redirectToLoginPage(store);
    if (willRedirect) {
      return willRedirect;
    }

    return {
      props: {
        pageData: {},
      },
    };
  });
