import Dashboard from "@pagesComps/Dashboard";
import Head from "next/head";
import { useAppSelector } from "redux/hooks";

//using google font
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { auth } = useAppSelector((state) => state);
  // eslint-disable-next-line no-console
  console.log(auth);
  return (
    <>
      <Head>
        <title>Newspaper - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
}
